### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by leewujung** [oceanhackweek/ohw-22-proj-earthquakes#1]
Hey @bartonnoah : could you change the repo name to follow the convention `ohw-22-proj-PROJECT_NAME` so that it is easier for others find and join? Thanks!

**Comment by bartonnoah** [comment]
Sorry about that, was unaware there was a convention.  Repo has been changed to `ohw-22-proj-earthquakes`.

**Comment by leewujung** [comment]
No worries, thank you!!
